CREATE TABLE [dbo].PHAN_HOI
(
	[ID] INT NOT NULL identity PRIMARY KEY, 
    [TIEU_DE] NVARCHAR(100) NOT NULL, 
    [HO_TEN] NVARCHAR(50) NULL, 
    [LIEN_HE] NVARCHAR(50) NULL, 
    [NOI_DUNG] NVARCHAR(1000) NOT NULL
)
