CREATE TABLE [dbo].[LOAI_HANG] (
    [MA_LOAI_HANG]  VARCHAR (10)   NOT NULL,
    [TEN_LOAI_HANG] NVARCHAR (128) NOT NULL,
    [HINH_ANH]      VARCHAR (128)  NULL,
    PRIMARY KEY CLUSTERED ([MA_LOAI_HANG] ASC)
);

